### ISSUE TITLE
Sign in with GitHub on the API page doesn't work. 

### ISSUE THREAD

**Issue by jameszhang-a** [Madgrades/api.madgrades.com#22]
I am signed in with GitHub, and I'm not provided a key after clicking the sign-in button.

**Comment by nandanv2702** [comment]
Hey! Facing the same issue here, I think it's related to incorrect credentials for the GitHub auth flow in the backend

<img width="703" alt="Screen Shot 2021-12-22 at 5 35 09 PM" src="https://user-images.githubusercontent.com/41271165/147090309-b40e3989-cb36-4277-b75e-b7ca51c57947.png">

**Comment by thekeenant** [comment]
Hello! Just got around to addressing this, give it another try if you're still interested.
